### ISSUE TITLE
Blog: issue with showing single entries

### ISSUE THREAD

**Issue by Torsten-K** [yuzoolcode/pulsecms-tracking#112]
Clicking onto a blog title on the blog main page to get to the single entry does not work. The links which are created by the system are wrong, like _pulse-5/blog/test-article/test-article_ (= duplicated blog page name). I receive an HTTP ERROR 500. In some cases, no error message appears, but I find myself still on the blog main page.

**Comment by ghost** [comment]
I have sub folder install so not that

Works for me

<img width="1119" alt="Screenshot 2019-09-29 at 11 55 27" src="https://user-images.githubusercontent.com/4608547/65825282-238bd980-e2b0-11e9-9afd-d2973399947b.png">
<img width="1119" alt="Screenshot 2019-09-29 at 11 55 40" src="https://user-images.githubusercontent.com/4608547/65825283-24247000-e2b0-11e9-9b23-41bf970dd8ea.png">

- can you provide a little more details?
- is this for new posts? 
- can you try the latest version 5.3.6?

Blog URLS were switched from 5.3.3:

> - URLs of the form blog/A-Very-Nice-Blog-Post or blog/subblog/A-Very-Nice-Blog-Post are now supported
> https://github.com/yuzoolcode/pulsecms-tracking/issues/102

And these went live in 5.3.5 
And should appear like "http://localhost:8888/pulsecms5ui/blog/A-Very-Nice-Blog-Post/5"

Let us know more if problem still persists

**Comment by Torsten-K** [comment]
I did a fresh install, deleted some pages (using admin backend), and when I visit my website, I receive a white page (This page does not work – too many redirects).  
The admin login is shown, but I get a long list of the following sentence: Access to this article is denied. Thus the login field is below the browser window, and I can’t scroll down. I gave the pages read permission. Okay, I could filter out these error messages with uBlock Origin, so I can log in at least.

Anyway, it had something to do with user groups. I guess I’ll have to dive deeper into this.

So, I can now test the behaviour of the blog and let you know, but it might take a few days or so.

**Comment by Torsten-K** [comment]
a)

One problem still exists:

The duplication has not changed (_https://www.[…]/pulse/blog/A-Very-Nice-Blog-Post/A-Very-Nice-Blog-Post_).

b)

The other problem at first also appeared again, but I finally found the error (see below):

After creating new user groups and users, I received a white page, like I described before. At least I could log into the administration backend. The preview worked and showed the web pages correctly. But I couldn’t log out (HTTP ERROR 500). I deleted the users and usergroups, deactivated the .htaccess file and deleted the cookies in the browser, but nothing helped. I could not even edit pages any longer (HTTP ERROR 500).

And the error was the following:

There were entries in _pulsecore/storage/config.json_, regarding permissions of usergroups. Unfortunately, I did not make a copy before deleting those entries, and thus I cannot post them here, but I will try to reproduce this, so that can post it here later.

**Comment by Torsten-K** [comment]
Solution for b) found: I had deleted the files in _pulsecore/cache_. Since restoring them, editing pages and blocks is possible again.

Problem a) is still present under Pulse 5.3.7, no matter if the blog posts are old or freshly created.

**Comment by Torsten-K** [comment]
Seems to have something to do with the meta data of blog articles. A part of the URL becomes duplicated when the link is being created, I guess.

![blog-metadaten](https://user-images.githubusercontent.com/806012/67944456-cbacff00-fbdc-11e9-9b3e-946233bd2ed8.png)

**Comment by ghost** [comment]
So problem B) has been solved for you @Torsten-K ?
Only problem A) persists?

**Comment by Torsten-K** [comment]
@yuzoolcode: Yes, exactly, only problem A) still exists. In the meantime, I took a look into the .htaccess file, but there does not seem to be a problem. I will test with a fresh installation, without changing anything, to see if the problem also exists then.

**Comment by Torsten-K** [comment]
Now I realize what my mistakes were:

- I don’t have to rename the URL in the meta settings (in the dashboard), not even change uppercase letters to lowercase letters.
– The name of the blog post in the dashboard should be a number, but not the actual blog title.

Having found out these things, everything works like a charm now.

I only must say, the way how URLs for blog posts are created, differs quite much from other content management or blog systems. As I am used to WordPress/ClassicPress, concrete5 and Bludit, I was quite confused, and I wonder why Pulse adds numbers or whatever behind the actual single blog post URL.

But anyway, now everything is clear and the thread can be closed. Thanks for your patience, Michael!

**Comment by ghost** [comment]
Thanks @Torsten-K and sorry for the confusion. That's just the way it has evolved throughout version 5 after getting feedback from current users.

We really appreciate your testing and feedback.

We have version 5.3.8 almost ready and hope it will be good for you also.

Bests
