### ISSUE TITLE
Clicking a navigation link shows the directory twice

### ISSUE THREAD

**Issue by oliver-77** [yuzoolcode/pulsecms-tracking#20]
When I click on a navigation link, I get an 404 Error.
This is because the the subfolder is showing twice in the URL.

![link](https://user-images.githubusercontent.com/24696577/35812590-b8818786-0a91-11e8-9c74-cfa91bb25043.png)

**Comment by ghost** [comment]
Could be related to
https://github.com/yuzoolcode/pulsecms-tracking/issues/16

**Comment by ghost** [comment]
Fixed in 5.0.3:
http://help.pulsecms.com/article/10-version-history

We did find an error which was skipping a slash in the url for sub-menus.

- redownload and make a fresh install of all files
- run the installer

Should work 😀

**Comment by oliver-77** [comment]
Problem still exists in a fresh install of v5.0.3

![link](https://user-images.githubusercontent.com/24696577/35927567-5b05fa4c-0c2b-11e8-869e-924242e10fd8.png)

**Comment by IvaRoSoft** [comment]
https://pulse5.000webhostapp.com/privacy  ok

**Comment by ghost** [comment]
Thanks @oliver-77 - can you confirm you're running 5.0.3? Check config.php and let me know 

If so, then please send the server logs and storage/cache logs :)
